services:
  - type: web
    name: tg-downloader-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.3
